"""Controlled variants of public formulas for the counter-recall arm (§7.2).

Every variant is generated by code, validated by the verifier, and stores the property it is meant
to change (SA, NL) or preserve (SP):

  SP  semantics-preserving: (i) notation translation, (ii) rename/inline intermediates,
      (iii) commutative reorder / algebraic identity, (iv) field anonymization with legend
      -> must be numerically equivalent to the base formula
  SA  semantics-altering: sign flip, window change, field swap -> must NOT be equivalent and the
      targeted property must change according to the verifier
  NL  misleading label on the unchanged formula -> the label's property must be REFUTED
"""
from __future__ import annotations

import random

from dsl import C, F, Node, canonical_equal, effective_lookback, walk
from dsl.ast import paths, replace_at, subtree
from dsl.fields import FIELDS
from dsl.operators import OPS
from dsl.serialize import anonymize_legend, to_alpha101, to_anonymized, to_math, to_notation, to_program, to_qlib

SP_TYPES = ("notation", "intermediates", "algebraic", "anonymized")
SA_TYPES = ("sign", "window", "field")

_SOURCE_NOTATION = {"alpha101": "alpha101", "gtja191": "gtja", "alpha158": "qlib"}
_TRANSLATE_TO = {"alpha101": "qlib", "gtja191": "qlib", "alpha158": "alpha101"}


# ------------------------------------------------------------------------------------------ SP
def _rewrite_once(node: Node, rng: random.Random) -> Node | None:
    cands = []
    for path, n in paths(node):
        if n.is_leaf:
            continue
        if n.op in ("Add", "Mul", "Greater", "Less", "Corr", "Cov", "And", "Or", "Eq", "Ne") and n.children[0] != n.children[1]:
            cands.append((path, Node(n.op, (n.children[1], n.children[0]), n.params)))
        if n.op == "Sub":
            cands.append((path, Node("Neg", (Node("Sub", (n.children[1], n.children[0])),))))
        if n.op == "Mean":
            cands.append((path, Node("Div", (Node("Sum", n.children, n.params), C(float(n.params[0]))))))
        if n.op == "Lt":
            cands.append((path, Node("Gt", (n.children[1], n.children[0]))))
        if n.op == "Gt":
            cands.append((path, Node("Lt", (n.children[1], n.children[0]))))
        if n.op == "Delta":
            x = n.children[0]
            cands.append((path, Node("Sub", (x, Node("Ref", (x,), n.params)))))
    if not cands:
        return None
    path, new = rng.choice(cands)
    return replace_at(node, path, new)


def algebraic_rewrite(node: Node, rng: random.Random, n_rewrites: int = 2) -> Node:
    out = node
    for _ in range(n_rewrites):
        nxt = _rewrite_once(out, rng)
        if nxt is not None:
            out = nxt
    return out


def sp_variant(base_node: Node, library: str, sp_type: str, seed: int) -> dict:
    """Return {"node", "presented", "notation", "legend", "perturbation"} for one SP type."""
    rng = random.Random(seed)
    src = _SOURCE_NOTATION.get(library, "qlib")
    legend = None
    node = base_node
    if sp_type == "notation":
        target = _TRANSLATE_TO.get(library, "math")
        if rng.random() < 0.34:
            target = "math"
        presented, notation = to_notation(base_node, target), target
    elif sp_type == "intermediates":
        presented = to_program(base_node, min_size=2, notation="alpha101" if src == "alpha101" else "qlib")
        notation = "program"
    elif sp_type == "algebraic":
        node = algebraic_rewrite(base_node, rng)
        presented, notation = to_notation(node, src), src
    elif sp_type == "anonymized":
        # legend over all panel fields so the glossary does not reveal which fields are used
        legend = anonymize_legend(base_node, seed, all_fields=True)
        presented = to_qlib(base_node, legend=legend)
        notation = "anonymized"
    else:
        raise ValueError(sp_type)
    return {"node": node, "presented": presented, "notation": notation, "legend": legend,
            "perturbation": {"type": f"sp_{sp_type}", "target_property": "all claims", "expected_change": "none"}}


# ------------------------------------------------------------------------------------------ SA
def _strip_outer_negation(node: Node) -> Node | None:
    if node.op == "Neg":
        return node.children[0]
    if node.op == "Mul":
        a, b = node.children
        if a.is_const and a.value == -1.0:
            return b
        if b.is_const and b.value == -1.0:
            return a
    return None


def sa_sign(node: Node) -> Node:
    """Negate the expression: remove an outer (-1 * ...) when present (natural-looking variant),
    otherwise wrap the formula in a negation."""
    inner = _strip_outer_negation(node)
    return inner if inner is not None else Node("Mul", (C(-1.0), node))


def _window_nodes(node: Node):
    out = []
    for path, n in paths(node):
        if not n.is_leaf and OPS[n.op].kind == "ts":
            out.append((path, n))
    return out


def _new_windows(n: int, min_window: int) -> list[int]:
    """Primary target first (e.g. 5 -> 60, 20 -> 5), then an alternative (-> 120 / -> 3)."""
    targets = [60, 120] if n <= 10 else [5, 3] if n >= 20 else [60, 120]
    return [max(t, min_window) for t in targets]


def sa_window(node: Node, rng: random.Random, rank: int = 0) -> tuple[Node, int, int] | None:
    """Change one lookback (e.g. 5 -> 60): prefer windowed operators on the max-lookback path.
    ``rank`` > 0 returns the rank-th alternative (a different window node) when one exists."""
    cands = _window_nodes(node)
    if not cands:
        return None
    L = effective_lookback(node)
    windowed = [c for c in cands if c[1].op not in ("Ref", "Delta")]
    pool = windowed or cands
    rng.shuffle(pool)
    pool.sort(key=lambda c: -int(c[1].params[0]))
    options = []
    for level in (0, 1):                       # all primary targets before any alternative target
        for path, n in pool:
            old = int(n.params[0])
            new = _new_windows(old, OPS[n.op].min_window)[level]
            if new != old:
                options.append((path, n, old, new))
    for path, n, old, new in options:
        new_node = Node(n.op, n.children, (new,) + tuple(n.params[1:]))
        out = replace_at(node, path, new_node)
        if effective_lookback(out) != L and not canonical_equal(out, node):
            if rank == 0:
                return out, old, new
            rank -= 1
    return None


_SWAPS = {"close": ("open", "vwap"), "open": ("close",), "high": ("low",), "low": ("high",),
          "volume": ("amount",), "amount": ("volume",), "vwap": ("close",)}


def _swap_field(node: Node, old: str, new: str) -> Node:
    if node.is_field:
        return F(new) if node.name == old else node
    if node.is_const:
        return node
    return Node(node.op, tuple(_swap_field(c, old, new) for c in node.children), node.params)


def sa_field(node: Node, rng: random.Random) -> list[tuple[Node, str, str]]:
    """Candidate type-compatible field swaps (close<->open, volume<->amount, high<->low), in random order."""
    present = sorted({n.name for n in walk(node) if n.is_field})
    cands = [(f, g) for f in present for g in _SWAPS.get(f, ()) if g in FIELDS]
    rng.shuffle(cands)
    out = []
    for old, new in cands:
        v = _swap_field(node, old, new)
        if not canonical_equal(v, node):
            out.append((v, old, new))
    return out


# ------------------------------------------------------------------------------------------ NL
# misleading-label bank: (label text, claim it asserts, codebook terms that express the same property).
# The claim must be REFUTED by the verifier on the panel; label following is detected when a rationale
# makes a resemblance/exposure claim with one of the terms (§11).
NL_LABELS = [
    ("20-day momentum", {"predicate": "RESEMBLES", "args": {"ref": "short-term momentum", "sign": "+"}},
     ["short-term momentum", "momentum", "trend"]),
    ("short-term reversal", {"predicate": "RESEMBLES", "args": {"ref": "short-term reversal", "sign": "+"}},
     ["short-term reversal", "reversal", "mean reversion"]),
    ("12-1 month momentum", {"predicate": "RESEMBLES", "args": {"ref": "momentum", "sign": "+"}}, ["momentum", "trend"]),
    ("low-volatility factor", {"predicate": "RESEMBLES", "args": {"ref": "low volatility", "sign": "+"}}, ["low volatility"]),
    ("high-volatility factor", {"predicate": "RESEMBLES", "args": {"ref": "volatility", "sign": "+"}},
     ["volatility", "idiosyncratic volatility"]),
    ("Amihud illiquidity", {"predicate": "RESEMBLES", "args": {"ref": "illiquidity", "sign": "+"}}, ["illiquidity"]),
    ("abnormal volume surprise", {"predicate": "RESEMBLES", "args": {"ref": "abnormal volume", "sign": "+"}},
     ["abnormal volume", "volume surprise"]),
    ("52-week-high proximity", {"predicate": "RESEMBLES", "args": {"ref": "52-week high", "sign": "+"}}, ["52-week high"]),
    ("lottery (MAX) effect", {"predicate": "RESEMBLES", "args": {"ref": "lottery", "sign": "+"}}, ["lottery", "max effect"]),
    ("overnight gap", {"predicate": "RESEMBLES", "args": {"ref": "overnight return", "sign": "+"}}, ["overnight return"]),
    ("intraday buying pressure", {"predicate": "RESEMBLES", "args": {"ref": "intraday pressure", "sign": "+"}},
     ["intraday pressure", "buying pressure"]),
    ("close-location value", {"predicate": "RESEMBLES", "args": {"ref": "close location", "sign": "+"}}, ["close location"]),
    ("price-volume correlation", {"predicate": "RESEMBLES", "args": {"ref": "price-volume correlation", "sign": "+"}},
     ["price-volume correlation"]),
    ("size (small-cap) factor", {"predicate": "RESEMBLES", "args": {"ref": "small size", "sign": "+"}}, ["small size", "size"]),
]


def nl_label(node: Node, ctx, rng: random.Random) -> tuple[str, dict, dict, list[str]] | None:
    """Pick a label whose asserted property the verifier REFUTES for this formula."""
    from verify.dispatcher import verify_claim
    from verify.verdicts import REFUTED

    bank = NL_LABELS[:]
    rng.shuffle(bank)
    for text, claim, terms in bank:
        v = verify_claim(claim, node, ctx)
        if v.verdict == REFUTED:
            label = f"Name: {text}" if text.endswith("factor") or text.endswith("effect") else f"Name: {text} factor"
            return label, claim, v.to_dict(), terms
    return None


def k_named_label(display_name: str) -> str:
    return f"Name: {display_name}"


__all__ = ["SP_TYPES", "SA_TYPES", "sp_variant", "sa_sign", "sa_window", "sa_field", "nl_label", "k_named_label",
           "algebraic_rewrite", "to_alpha101", "to_qlib", "to_math", "subtree"]
